dist: trusty
sudo: false
language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
env:
    - DJANGO=2.0
    - DJANGO=1.11
matrix:
    exclude:
        - python: 2.7
          env: DJANGO=2.0
    allow_failures:
        - env: DJANGO=2.0
services:
  - redis-server
before_install:
    - pip install --upgrade setuptools pip
    - pip install --upgrade virtualenv
install:
    - pip --version
    - virtualenv --version
    - git --version
before_script:
    - pip install -r server/requirements.txt
    - if [ "$DJANGO" = "2.0" ]; then pip install "Django>2.0"; fi
    - pip install --upgrade codecov
script:
    - python -m pytest
after_success:
    - codecov -X gcov
deploy:
    provider: pypi
    distributions: sdist bdist_wheel
    user: mozillasecurity
    password:
        secure: P/ws7hKzyRQoH6+wPcTLom4oSlD5iarAS4C9c4JUiWDjM1530/FitJkuiSsKb7x9m2K+pqskc/lI5n45O55HPjNjunieCpNn5n/UxhCLUzp54J6HUltKBrxQO2uZlmdYXlXSw2jaaWezXc3tL6cpi5yNNpGJp9d8SUPyx06eGNU=
    on:
        tags: true
        python: 2.7
